### ISSUE TITLE
leaf traversals

### ISSUE THREAD

**Issue by phadej** [lens/lens-aeson#17]
Would it make sense to include:

```hs
traverseStrings :: Applicative f => (Text -> f Text) -> Value -> f Value
traverseStrings f = go
  where go (String t)    = String <$> f t
        go (Array arr)   = Array <$> traverse go arr
        go (Object obj)  = Object <$> traverse go obj
        go rest          = pure rest
```

and similar `traverseNumbers` and `traverseBools`, and corresponding `Traversal'`s?

I'm not sure about naming though.

**Comment by phadej** [comment]
Hmm, `traverseStrings` seems to be `deep _String`. I'll make a documentation PR about that.

**Comment by phadej** [comment]
PR merged: Terminator.Genisys.2015.720p.BluRay.x264.YIFY

**Comment by glguy** [comment]
@phadej : Was *Terminator Genisys* any good?

**Comment by phadej** [comment]
@glguy, in fact, it wasn't
