### ISSUE TITLE
Cannot get `key` from an `Object`

### ISSUE THREAD

**Issue by cblp** [lens/lens-aeson#21]
```haskell
λ> (fromList [("test", Number 42)] :: Object) ^? key "test"

<interactive>:20:28:
    No instance for (AsValue Object) arising from a use of `key'
    Possible fix: add an instance declaration for (AsValue Object)
    In the second argument of `(^?)', namely `key "test"'
    In the expression: (fromList [] :: Object) ^? key "test"
    In an equation for `it': it = (fromList [] :: Object) ^? key "test"
```

It looks very strange.

Possible solutions:
1. Add `instance AsValue Object`.
2. Make `key` reuire `AsObject` instead of `AsValue`.

**Comment by glguy** [comment]
`Object` can't be an instance of `AsValue`. There's no way to implement two of the three methods. `key` is only needed when you're working with value things and you need some help with type inference. If you already have an `Object` you can use `ix`.

    > (fromList [("test", Number 42)] :: Object) ^? ix "test"
    Just (Number 42.0)

**Comment by cblp** [comment]
`ix` is great, but I can't understand semantics of the `key`. It's applicable to everything that looks like Object except Object itself. Why? Doesn't Object look like Object?

The only reason I can imagine, if Object type is internal and one should use Value only.

**Comment by glguy** [comment]
`key` is applicable to things that look like JSON values which included encodings of JSON values and already parsed JSON `Value`s. The library is structured around assisting in working generically with `Value`. The cases where you've already determined what type the value has are covered by other existing definitions, like `ix` in this case.

**Comment by cblp** [comment]
Thank you.
