### ISSUE TITLE
aeson 0.11.0.0 not supported with lens-aeson

### ISSUE THREAD

**Issue by andygill** [lens/lens-aeson#22]
Can we bump the bounds of lens-aeson to support aeson 0.11? The current bounds are stopping the major package wreq from compiling, which is stopping our libraries from compiling with aeson.

Cheers!

- Andy

**Comment by glguy** [comment]
Fixed in fd34832b711c00867396b832a1cfcd21af14e6c3 and on hackage in 1.0.0.5
