### ISSUE TITLE
Doctests fail on 32-bit archs

### ISSUE THREAD

**Issue by iliastsi** [lens/lens-aeson#30]
Doctests fail on 32-bit archs (e.g., [i386](https://buildd.debian.org/status/fetch.php?pkg=haskell-lens-aeson&arch=i386&ver=1.0.2-5&stamp=1541092359&raw=0), [armel](https://buildd.debian.org/status/fetch.php?pkg=haskell-lens-aeson&arch=armel&ver=1.0.2-5&stamp=1541091922&raw=0), etc) with the following error:
```
Running 1 test suites...
Test suite doctests: RUNNING...
/<<PKGBUILDDIR>>/src/Data/Aeson/Lens.hs:331: failure in expression `"{\"a\": 4, \"b\": 7}" ^@.. members'
expected: [("a",Number 4.0),("b",Number 7.0)]
 but got: [("b",Number 7.0),("a",Number 4.0)]
```

**Comment by glguy** [comment]
Oops, we shouldn't be relying on the order of elements stored in a hash map!
