### ISSUE TITLE
Support aeson-2.0.0.0

### ISSUE THREAD

**Issue by phadej** [lens/lens-aeson#37]
https://github.com/phadej/aeson-optics/commit/ff31ca0578482df11002f0cde974ff51b8559e1c is what I did for `aeson-optics`

**Comment by RyanGlScott** [comment]
Thanks for the heads-up. I do wonder `_Object` should eventually focus on a `KeyMap` rather than a `HashMap` (see #38), but it's probably too early to think about that. Until then, I'll prepare a PR based off of your `aeson-optics` patch.

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. If you don't mind, please shout on #38 when you make (or are about to make) such changes on `aeson-optics`' side—I can make corresponding changes on the `lens-aeson` side at the same time.

**Comment by RyanGlScott** [comment]
See #39 for a fix.

**Comment by RyanGlScott** [comment]
I've uploaded [`lens-aeson-1.1.2`](https://hackage.haskell.org/package/lens-aeson-1.1.2) to Hackage with the changes in #39.
