### ISSUE TITLE
category: Numeric is probably wrong

### ISSUE THREAD

**Issue by phadej** [lens/lens-aeson#51]
... which you can correct with a revision

FYI: there's aeson-2.1 release too, which shouldn't need any code changes to `lens-aeson`, so can be done in the same revision.

**Comment by RyanGlScott** [comment]
True. I wonder what the right category should be. Data? Lenses? JSON? All of the above? Something else?

**Comment by phadej** [comment]
[`aeson-optics`](https://hackage.haskell.org/package/aeson-optics) has `Data, JSON, Optics`, so `Data, JSON, Lenses` sounds right.

**Comment by RyanGlScott** [comment]
Sounds good to me. I've [revised `lens-aeson-1.2.1`](https://hackage.haskell.org/package/lens-aeson-1.2.1/revisions/) to reflect these categories, and I've relaxed the upper version bounds on `aeson` to allow `2.1.*` as well.
